{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "onprem-dlp.serviceAccountName" . }}
  labels:
    {{- include "onprem-dlp.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
